### ISSUE TITLE
Initiation error

### ISSUE THREAD

**Issue by Saicopate** [maeneak/utecio-ha#37]
## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1385
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 9.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), Mosquitto broker (6.4.1), File editor (5.8.0), Cloudflared (5.1.15), Silicon Labs Multiprotocol (2.4.5), Zigbee2MQTT (1.39.0-1), Node-RED (18.0.4), ESPHome (2024.6.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6 lipca 2024 03:37
-- | --
current_recorder_run | 12 lipca 2024 18:15
estimated_db_size | 59.82 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/maeneak/ultraloq_ble/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi,

thanks for this integration. However initition fails with the following error:

Anything to check ?

### Reproduction steps

1.Install integration
2. Login to u home account
3. Initiate integration

### Debug logs

```text
`Rejestrator: homeassistant.config_entries
Źródło: config_entries.py:586
Pierwsze zdarzenie: 12 lipca 2024 18:15:37 (2 zdarzenia)
Ostatnio zalogowany: 11:42:35

Error setting up entry Ultraloq Bluetooth for ultraloq_ble
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ultraloq_ble/__init__.py", line 33, in async_setup_entry
    devices = await client.get_ble_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/utecio/api.py", line 190, in get_ble_devices
    if device.capabilities.bluetooth:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'GenericLock' has no attribute 'bluetooth'`
```

**Comment by rxritalin** [comment]
Im seeing the same error. 

I have the bridge but its not currently connected. I assume this is the way it should be?

**Comment by brayStorm** [comment]
Same exact error on my end

**Comment by inventor7777** [comment]
Hi @Saicopate @rxritalin @brayStorm  I forked the integration and gave it U-Bolt Pro support. I don't have any other types of Ultraloq locks but I would be curious if it works with yours. https://github.com/inventor7777/ultraloq-ble-ha

Of course, it has been YEARS so the chances that you guys are still interested is low, but never zero :)
